AWSTemplateFormatVersion: "2010-09-09"
Description:
  DDB used by our application.
Parameters:
  ReadCapacity:
    Type: Number
    Default: 5
  WriteCapacity:
    Type: Number
    Default: 5
Resources:
  TinifyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: urlHash
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: urlHash
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacity
        WriteCapacityUnits: !Ref WriteCapacity
Outputs:
  TableName:
    Value: !Ref TinifyTable